apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  labels:
    cloud: auto-detect
    vendor: auto-detect
  name: '{{ .Values.clusterClaimName }}' # doesn't matter what this is, it will be ignored
  namespace: '{{ .Values.clusterClaimName }}' # doesn't matter what this is, it will be ignored
  annotations:
    argocd.argoproj.io/sync-wave: "370"
    helm.sh/hook-weight: "370"
spec:
  hubAcceptsClient: true
