apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure
spec:
  data:
  - secretKey: azureBaseDomain
    remoteRef:
      key: 094b9d3e-c841-959e-d70f-2fbe86f6ec0d 
  - secretKey: azureBaseDomainResourceGroupName
    remoteRef:
      key: 77ae31bf-d4c7-cf6e-45c7-de5d7bdae1ba 
  - secretKey: azureOsServicePrincipal
    remoteRef:
      key: ef8a9c51-6300-ff8a-2aa4-aef4c9d8b166 
  - secretKey: openshiftPullSecret
    remoteRef:
      key: c3822044-3fb0-8865-ac9f-abff19763d59
  - secretKey: openshiftSSHPrivateKey
    remoteRef:
      key: 579f0dfb-1a65-087d-5710-8d7eca29c8b7
  - secretKey: openshiftSSHPublicKey
    remoteRef:
      key: e54f376c-1d17-6e98-76dc-a9f4a6369716
  refreshInterval: 24h0m0s
  secretStoreRef:
    name: cluster
    kind: ClusterSecretStore
  target:
    name: azure
    creationPolicy: Owner
    template:
      metadata:
        labels:
          cluster.open-cluster-management.io/credentials: ""
          cluster.open-cluster-management.io/type: azr
      type: Opaque
      data:
        baseDomain: "{{ .azureBaseDomain | toString }}"
        baseDomainResourceGroupName: "{{ .azureBaseDomainResourceGroupName | toString }}"
        cloudName: AzurePublicCloud
        osServicePrincipal.json: "{{ .azureOsServicePrincipal | toString }}"
        pullSecret: "{{ .openshiftPullSecret | toString }}"
        ssh-publickey: "{{ .openshiftSSHPublicKey | toString }}"
        ssh-privatekey: "{{ .openshiftSSHPrivateKey | toString }}"